### ISSUE TITLE
support counters

### ISSUE THREAD

**Issue by trevorwhitney** [cloudfoundry/statsd-injector#4]
The statsd_injector takes puts all metrics into the firehose as guage/value metrics regardless of how they're defined in the statsd string (ie. counter, gauge, etc.) Can it support counters?

**Comment by AmberAlston** [comment]
An example Cloud Foundry use case this issue is impacting - `uaa.requests.global.completed.count` is emitted as a counter metric in the more recent UAA releases. This is being sent correctly, however it is transmitting out of the firehose as `eventType:ValueMetric` instead of`eventType:CounterEvent`. This is impacting downstream metric consumers. If more component teams are to adopt statsd-injector, then it should support all of the possible loggregator envelope types.

**Comment by MasslessParticle** [comment]
We looked into this and, unfortunately, StatsD counters must be emitted as Loggregator gauges. In StatsD, the counter type can be incremented or decremented while the Loggregator counters only ever increase.

**Comment by ahevenor** [comment]
To articulate further, the closest equivalent of the statsd implementation of a counter in the Loggregator API is a gauge. We intentionally convert these to counters to gauges to account for this. We also considered dropping (intentionally) counters received in the statsd injector but because the statsd protocol is UDP based, the producer (e.g. UAA) would not know they were being dropped so conversion seems like a better option. To support the Loggregator counter envelope the producer would have to use one of our clients like [go loggregator](https://github.com/cloudfoundry/go-loggregator) or there is some work done towards a java client in the new jmx nozzle that could be helpful to UAA.

cc @AmberAlston

**Comment by trevorwhitney** [comment]
The java community seems to be standardizing on the [Dropwizard](http://metrics.dropwizard.io/4.0.0/) format, and the cf java buildpack will automatically send Dropwizard metrics to the the metrics forwarder if it's available. It'd be great if we could work towards a solution that could convert Dropwizard metrics to the appropriate envelopes to be sent to loggregator. In the meantime, understood about the statsd limitations, thanks for looking into it @ahevenor.
