### ISSUE TITLE
Support tagging

### ISSUE THREAD

**Issue by jtuchscherer** [cloudfoundry/statsd-injector#5]
Inspired by the discussion of https://github.com/cloudfoundry/istio-release/pull/11 

StatsD does not really support tags, it is only some forks that added support for tags (here is an issue for that: https://github.com/statsd/statsd/issues/619).
We could do something similar like datadog or influx did for the stats-injector. When comparing the syntax that DataDog chose (see here for an exmaple: https://github.com/DataDog/datadog-agent/blob/master/pkg/dogstatsd/parser_test.go#L188-L200) with the one from InfluxDB, I have to say, I prefer the InfluxDB one, but I am open to suggestions.

**Comment by kramerul** [comment]
For our use case, the DataDog syntax would be better, because [Envoy](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto#config-metrics-v2-dogstatsdsink) and [istio](https://istio.io/docs/reference/config/policy-and-telemetry/adapters/datadog/) directly support this statsd extension. Otherwise, we would need to use a converter in between.

Also for other network proxies like nginx, it seems to be easier to use the datadog dialect to collect data including tags (search  for "nginx statsd tags" using google).

**Comment by kramerul** [comment]
Perhaps, supporting both would be an option. You can simply distinguish the dialect by the number of "|" characters.

**Datadog**
```
metric:666|g|#sometag1:somevalue1,host:my-hostname,sometag2:somevalue2
```
**Influxdb**
```
metric,sometag1=somevalue1,host=my-hostname,sometag2=somevalue2:666|g
```

**Comment by jtuchscherer** [comment]
I am fine with supporting the Datadog standard if that has a wider adoption and support. We can explore supporting both, but I am would prefer to only go one route to avoid code complexity and confusion.

**Comment by jtuchscherer** [comment]
This is now supported in the latest statsd-injector release:
https://github.com/cloudfoundry/statsd-injector-release/releases/tag/v1.8.0
